### ISSUE TITLE
commit: definir nomenclatura

### ISSUE THREAD

**Issue by gianfranco-s** [maxiyommi/labo_inteligente#7]
Por ejemplo:
* [UPDATE]
* [FIX], etc.

Tal vez en `contributing.md`

**Comment by mantiagosartinez** [comment]
Encontré esta convención y buscando en varios links me llevaron a este link:
https://www.conventionalcommits.org/en/v1.0.0/#summary

En base a esta convención y a nuestra aplicación propongo que tengamos:

feat, fix, docs, test

feat para cuando haya un cambio. fix cuando se arregle algún bug o algún error de un commit previo. docs cuando se hagan cambios de documentación, ya sea de docstring o de md. test para cuando se hagan agreguen o se hagan modificaciones en los test del código

Luego el link propone el uso de un ! para cuando el commit tiene mayor relevancia

Paralelamente habria que definir si los commits los hacemos 100% en ingles.

También adjunto otro link en donde habla más sobre como hacer commits con un resumen y con un texto más extenso https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

**Comment by mantiagosartinez** [comment]
El ! se usa cuando es un cambio importante en el código que puede llevar a que no funcione. Sirve para que al revisarse en el PR no se lo pase por arriba y se concentre en el commit que puede provocar un cambio radical en el proyecto

**Comment by gianfranco-s** [comment]
Copiar a contributing.md
Linkear a Notion

**Comment by mantiagosartinez** [comment]
Ejemplo:
git commit -m "feat: allow a new service"
